version: "3.4"

services:
  web-react:
    build:
      context: .
      dockerfile: ./config/dockerfiles/Dockerfile-node
      args:
        APP_PATH: ./services/web-react
    ports:
      - '3000:3000'
    volumes:
      - ./services/web-react:/app
    command: "npm start"
    depends_on:
      - lambda-go
  lambda-go:
    build:
      context: .
      dockerfile: ./config/dockerfiles/Dockerfile-lambda-go
      args:
        SERVICE_PATH: ./services/lambda-go
        APP_PATH: src/github.com/vleango
    command: sam local start-api --docker-network notfamoustitle_default --docker-volume-basedir "$PWD/services/lambda-go/src/github.com/vleango" --host 0.0.0.0
    ports:
      - '4000:3000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/aws:/root/.aws
      - ./services/lambda-go/src:/go/src
      - ./services/web-react/build:/go/src/github.com/vleango/client/dist
    env_file:
      - config/environments/.aws.env
