service: helloruby

provider:
  name: aws
  runtime: ruby2.5
  region: ${file(./.${self:provider.stage}.yml):REGION}
  stage: ${opt:stage, 'development'}
  timeout: 10

package:
 exclude:
   - ./**
 include:
   - handler.rb
   - vendor/**/*

plugins:
  - serverless-sam

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
          cors: true
