service: aws-go-dep # NOTE: update this with your service name

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  region: us-west-2

package:
 exclude:
   - ./**
 include:
   - ./bin/**

plugins:
  - serverless-sam
  - serverless-finch

custom:
  client:
    bucketName: www.notfamoustitle.com
    errorDocument: index.html
    objectHeaders:
      index.html:
        - name: Cache-Control
          value: max-age=0

functions:
  hello:
    handler: bin/hello
    events:
      - http:
          path: hello
          method: get
  world:
    handler: bin/world
    events:
      - http:
          path: world
          method: get
