FROM node:9.11.1

# required to be passed in
ARG APP_PATH

ARG INSTALL_PATH=/app
ARG LOCAL_USER=node

# Create a directory where our app will be placed
RUN mkdir -p $INSTALL_PATH

# Change directory so that our commands run inside this new directory
WORKDIR $INSTALL_PATH

# Comment out if starting a new project
###################################################
COPY $APP_PATH/package.json $APP_PATH/yarn.lock ./
###################################################

# Install dependencies (yarn installed from node image)
RUN yarn install

# Install global packages with local user
USER $LOCAL_USER

# Get all the code needed to run the app
COPY $APP_PATH/. $INSTALL_PATH/.

CMD ["yarn", "run", "start"]
