FROM lambci/lambda:ruby2.5
FROM ruby:2.5.0

# required to be passed in
ARG SERVICE_PATH
ARG APP_PATH
ARG INSTALL_PATH=/ruby
ARG LOCAL_USER=ruby

# Install Nodejs
RUN curl -sL https://deb.nodesource.com/setup_9.x | bash -
RUN apt-get install -y nodejs

# Install Serverless
RUN npm i -g serverless@1.34.1

# Install python
RUN apt-get install -y -qq python-pip

# Install AWS SAM CLI
ENV PATH=$PATH:/root/.local/bin
RUN pip install --user aws-sam-cli

# Comment out when starting a new project
COPY $SERVICE_PATH/package.json $INSTALL_PATH/package.json
COPY $SERVICE_PATH/package-lock.json $INSTALL_PATH/package-lock.json

WORKDIR $INSTALL_PATH
RUN npm install

# copy project to container
COPY $SERVICE_PATH/. $INSTALL_PATH/.

# Install global packages with local user
RUN useradd -ms /bin/bash $LOCAL_USER
RUN usermod -aG sudo $LOCAL_USER
# can't set user... SAM: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/_ping: dial unix /var/run/docker.sock: connect: permission denied
#USER $LOCAL_USER

CMD ["npm", "start"]
